### ISSUE TITLE
TableTools Extension

### ISSUE THREAD

**Issue by nadrianm** [fedemotta/yii2-widget-datatables#1]
Hello budy, I'm working with DataTables in a Yii2 Advanced Application, and I was wondering If I could integrate TableTools Extension with your plug-in. Do you know how to do it? If there is another way to do data export (PDF, CSV, ...) I will be grateful if you give me an example.

Here is the extension doc. https://www.datatables.net/extensions/tabletools/

I'm looking forward to hearing from you!

**Comment by fedemotta** [comment]
Hi @nadrianm,
It should be pretty straightforward. We should add a new asset to yii2-widget-datatables with the TableTools plugin (like the bootstrap asset added in v1.1) and then you could use it using the clientOptions array. I will try to add the asset ASAP or feel free to add a PR.

Cheers

**Comment by fedemotta** [comment]
Closed via 3e0d4350f49405d2e6cd08e7b7e553eba0529963
