### ISSUE TITLE
responsive option not work

### ISSUE THREAD

**Issue by nJuraev** [fedemotta/yii2-widget-datatables#12]
my code
`DataTables::widget([
    'dataProvider'=>$dataProvider,
    'filterModel'=>$searchModel,
    'clientOptions' => [

```
"lengthMenu"=> [[ 25, 50,-1], [ 25, 50, "All"] ],
"info"=>false,
"responsive"=>true
```

   ],`
but when i change browser size table not collapsible.

**Comment by abalest14** [comment]
maybe you have resolved but can help somebody else, i have discover the responsive is an extension of datatables, i have resolved the problem including the JS and CSS from this page:
https://datatables.net/download/release

**Comment by fedemotta** [comment]
Thanks @abalest14

**Comment by indigitale** [comment]
> maybe you have resolved but can help somebody else, i have discover the responsive is an extension of datatables, i have resolved the problem including the JS and CSS from this page:
> https://datatables.net/download/release

can you help me? where have you included the js and css? thanks!
