### ISSUE TITLE
records limit as 20

### ISSUE THREAD

**Issue by tehnn** [fedemotta/yii2-widget-datatables#2]
Why the records are limit at 20?

**Comment by fedemotta** [comment]
@tehnn Because it is default value in the dataProvider. 

It is possible to disable pagination in your search method like this:

``` php
$dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => false,
        ]);
```

I am not sure to use pagination disabled by default. It could lead to slow queries. What do you think?

**Comment by tehnn** [comment]
Thank you. It 's solved.

**Comment by fedemotta** [comment]
@tehnn See ee0c70a038302ca414fe01d51732ed217efdc772. No need to add the pagination=>false anymore.

Filter, sort and pagination is being handled by DataTables in the JS layer now.
