### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by nordkite** [fedemotta/yii2-widget-datatables#3]
Cannot install this extension with Composer. I am getting error 
Problem 1
    - fedemotta/yii2-widget-datatables v1.3 requires bower-asset/datatables >= 1.9.4 -> no matching package found.
    - fedemotta/yii2-widget-datatables v1.2 requires bower-asset/datatables >= 1.9.4 -> no matching package found.
    - fedemotta/yii2-widget-datatables v1.1 requires bower-asset/datatables \* -> no matching package found.
    - fedemotta/yii2-widget-datatables v1.0 requires bower-asset/datatables \* -> no matching package found.
    - Installation request for fedemotta/yii2-widget-datatables \* -> satisfiable by fedemotta/yii2-widget-datatables[v1.0, v1.1, v1.2, v1.3]

**Comment by fedemotta** [comment]
@KirillRyzhkov  Try to run:
composer global require "fxp/composer-asset-plugin:~1.0.0"

Let me know if it works.
Cheers!

**Comment by nordkite** [comment]
Hi, fedemotta. I installed asset plugin but now I am getting this error asking me to enter a Token?
Reading bower.json of bower-asset/datatables (1.9.0)
Could not fetch https://api.github.com/repos/DataTables/DataTables/contents/bower.json?ref=2b126277fcc594174add7407fee2189c4aac980b, please create a GitHub OAuth token to go over the API rate limit
.........
Token (hidden):

**Comment by fedemotta** [comment]
Try a composer self-update and try again. If the problem persist try the
version 1.0.1 of the global plugin, I remember some issues with the latest
version of the global plugin. Let me know if it works.

Cheers

**Comment by nordkite** [comment]
Ok, extension is installed. Thanks for help.
